/**
 * Workflow graph generator
 *
 * Reads agents/sm.json and writes a Mermaid flowchart to
 * docs/agents/workflow.md. This is a prototype: it draws one node per rule
 * and shows status -> agent -> target status edges where a targetStatus is
 * declared.
 *
 * Usage:
 *   dmtools run agents/js/unit-tests/run_agentDocs.json
 *   node agents/js/agentWorkflowGraph.js   (Node, not GraalJS)
 */

var fs = require('fs');
var path = require('path');

var SM_JSON = 'agents/sm.json';
var WORKFLOW_MD = 'agents/docs/agents/workflow.md';

function readJson(filePath) {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function statusNode(status) {
    var safe = status.replace(/[^a-zA-Z0-9]/g, '_');
    return 'S_' + safe + '["' + status + '"]';
}

function agentNode(configFile, idx) {
    var name = configFile.replace(/^agents\//, '').replace(/\.json$/, '');
    return 'A' + idx + '_[' + name + ']';
}

function generate() {
    var sm = readJson(SM_JSON);
    var rules = (sm && sm.params && sm.params.rules) || [];

    var lines = [];
    lines.push('# dmtools-agents workflow (generated)');
    lines.push('');
    lines.push('```mermaid');
    lines.push('flowchart TD');

    var usedStatuses = {};
    var usedAgents = {};

    rules.forEach(function(rule, idx) {
        if (!rule.enabled) return;
        var agent = agentNode(rule.configFile, idx);
        usedAgents[agent] = true;

        // Source statuses from JQL heuristics
        var sourceStatuses = [];
        if (rule.jql) {
            var statusMatch = rule.jql.match(/status\s+in\s+\(([^)]+)\)/i);
            if (statusMatch) {
                sourceStatuses = statusMatch[1].split(',').map(function(s) {
                    return s.trim().replace(/^'|'$/g, '').replace(/^"|"$/g, '');
                });
            } else {
                statusMatch = rule.jql.match(/status\s*=\s*['"]([^'"]+)['"]/i);
                if (statusMatch) sourceStatuses.push(statusMatch[1]);
            }
        }

        sourceStatuses.forEach(function(status) {
            usedStatuses[status] = true;
            lines.push('    ' + statusNode(status) + ' --> ' + agent);
        });

        if (rule.targetStatus) {
            usedStatuses[rule.targetStatus] = true;
            lines.push('    ' + agent + ' --> ' + statusNode(rule.targetStatus));
        }
    });

    lines.push('```');
    lines.push('');
    lines.push('---');
    lines.push('_Generated by js/agentWorkflowGraph.js_');

    fs.writeFileSync(WORKFLOW_MD, lines.join('\n'));
    console.log('✅ Generated', WORKFLOW_MD);
    return { success: true, rules: rules.length };
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { generate };
}

if (require.main === module) {
    generate();
}
