/**
 * Agent documentation generator
 *
 * Reads every agent JSON file in agents/ and writes a per-agent Markdown page
 * to docs/agents/generated/<agent>.md. The generated pages are intentionally
 * concise; the human-curated docs/agents/index.md remains the canonical catalog.
 *
 * Usage:
 *   dmtools run agents/js/unit-tests/run_agentDocs.json
 *   node agents/js/agentDocGenerator.js   (Node, not GraalJS)
 */

var fs = require('fs');
var path = require('path');

var AGENTS_DIR = 'agents';
var DOCS_DIR = path.join(AGENTS_DIR, 'docs', 'agents', 'generated');

function ensureDir(dir) {
    try {
        fs.mkdirSync(dir, { recursive: true });
    } catch (e) {
        // ignore
    }
}

function listAgentConfigs() {
    var files = fs.readdirSync(AGENTS_DIR);
    return files.filter(function(f) {
        return f.endsWith('.json') &&
            f !== 'sm.json' &&
            f !== 'sm_merge.json' &&
            !f.startsWith('run_') &&
            f.indexOf('_lock') === -1;
    }).sort();
}

function readJson(filePath) {
    try {
        return JSON.parse(fs.readFileSync(filePath, 'utf8'));
    } catch (e) {
        console.warn('Could not parse', filePath, ':', e.message);
        return null;
    }
}

function escapeMd(text) {
    if (!text) return '';
    return String(text).replace(/\|/g, '\\|').replace(/\n/g, '<br>');
}

function renderOutputSchemas(outputSchemas) {
    if (!outputSchemas || typeof outputSchemas !== 'object') return '';
    var keys = Object.keys(outputSchemas);
    if (keys.length === 0) return '';
    var out = '### Output schemas\n\n';
    keys.forEach(function(fileName) {
        var schema = outputSchemas[fileName];
        out += '- `' + fileName + '`\n';
        if (schema.required && schema.required.length) {
            out += '  - required: `' + schema.required.join('`, `') + '`\n';
        }
    });
    return out + '\n';
}

function renderAgentDoc(fileName, config) {
    var params = config.params || {};
    var metadata = params.metadata || {};
    var customParams = params.customParams || {};
    var prompts = params.cliPrompts || [];
    var outputSchemas = params.outputSchemas || null;

    var name = config.name || metadata.contextId || fileName.replace(/\.json$/, '');
    var contextId = metadata.contextId || '—';
    var ticketType = params.inputJql ? 'see inputJql' : '—';
    if (params.ticketContextDepth !== undefined) {
        ticketType += ' (contextDepth=' + params.ticketContextDepth + ')';
    }

    var lines = [];
    lines.push('# ' + name + ' (`' + fileName + '`)');
    lines.push('');
    lines.push('| Attribute | Value |');
    lines.push('|---|---|');
    lines.push('| ContextId | `' + contextId + '` |');
    lines.push('| outputType | `' + (params.outputType || '—') + '` |');
    lines.push('| skipAIProcessing | `' + (params.skipAIProcessing || false) + '` |');
    lines.push('| preJSAction | `' + (params.preJSAction || '—') + '` |');
    lines.push('| preCliJSAction | `' + (params.preCliJSAction || '—') + '` |');
    lines.push('| postJSAction | `' + (params.postJSAction || '—') + '` |');
    lines.push('');

    if (Object.keys(customParams).length > 0) {
        lines.push('## Custom params');
        lines.push('');
        Object.keys(customParams).forEach(function(k) {
            lines.push('- `' + k + '`: `' + escapeMd(JSON.stringify(customParams[k])) + '`');
        });
        lines.push('');
    }

    if (prompts.length > 0) {
        lines.push('## Prompts / instructions');
        lines.push('');
        prompts.forEach(function(p) {
            lines.push('- `' + p + '`');
        });
        lines.push('');
    }

    var schemasMd = renderOutputSchemas(outputSchemas);
    if (schemasMd) {
        lines.push(schemasMd);
    }

    lines.push('---');
    lines.push('_Generated by js/agentDocGenerator.js_');
    return lines.join('\n');
}

function generate() {
    ensureDir(DOCS_DIR);
    var files = listAgentConfigs();
    console.log('Generating docs for', files.length, 'agent(s)');

    files.forEach(function(fileName) {
        var filePath = path.join(AGENTS_DIR, fileName);
        var config = readJson(filePath);
        if (!config) return;

        var doc = renderAgentDoc(fileName, config);
        var outPath = path.join(DOCS_DIR, fileName.replace(/\.json$/, '.md'));
        fs.writeFileSync(outPath, doc);
        console.log('✅', outPath);
    });

    return { success: true, generated: files.length };
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { generate };
}

if (require.main === module) {
    generate();
}
