'use strict';
/**
 * Pack runtime LOAD self-test generator (gh-823, extends the gh-812 gate).
 *
 * The gh-812 require gate is a STATIC scan; gh-823 proved a second class it
 * cannot see: code whose DEFERRED requires resolve against a different base
 * than its load-time ones. This module generates the probe that loads every
 * packed .js in the REAL dmtools runtime after the zip is built — any
 * require/parse failure at load fails the release (the caller runs
 * `dmtools run` on the generated config inside the extracted pack and
 * treats a non-zero exit as a failed release).
 *
 * Pure string/JSON generation — no fs, no exec: the caller
 * (ci/release_packs.mjs) owns the zip walk and the dmtools invocation, the
 * same split as pack_require_gate.cjs. Unit-testable in the dmtools runner.
 *
 * The probe itself is authored for the pack runtime's rules (see
 * test_packRequirePath.js): the generated file IS the main script, so its
 * own `require`s resolve against the pack's js/ root, and every REQUIRED
 * module gets the runtime's real init-time (file-relative) semantics.
 * Deferred requires do not fire at load — that class stays with the static
 * deferred-require gate; this probe catches parse errors and load-time
 * resolution misses in the exact runtime the fa ticks will run.
 */

/**
 * The js paths the probe will require: every packed .js except the probe
 * itself (which is generated into the pack root). Sorted for deterministic
 * output. [paths] is any iterable of zip-layout paths (array or Set).
 */
function probeFilesList(paths, probeName) {
    var out = [];
    var seen = {};
    var push = function (p) {
        if (!p || seen[p]) return;
        seen[p] = true;
        if (p === probeName) return;
        if (p.indexOf('.js') !== p.length - 3) return;
        if (p.indexOf('js/') !== 0) return;
        out.push(p);
    };
    var add = typeof paths.forEach === 'function'
        ? function (arr) { arr.forEach(push); }
        : function (obj) { for (var k in obj) push(k); };
    add(paths);
    return out.sort();
}

/** The generated probe source: requires every file, reports, throws. */
function renderProbeJs(files) {
    var lines = [
        '// GENERATED by ci/pack_load_probe.cjs — pack runtime load self-test (gh-823).',
        '// Requires every packed .js in the REAL dmtools runtime; any load or',
        '// parse failure fails the release (the runner exits non-zero).',
        'var FILES = ' + JSON.stringify(files) + ';',
        'var required = 0;',
        'var failed = [];',
        'for (var i = 0; i < FILES.length; i++) {',
        '    try {',
        '        require(FILES[i]);',
        '        required += 1;',
        '    } catch (e) {',
        '        failed.push(FILES[i] + " :: " + (e && e.message ? e.message : e));',
        '    }',
        '}',
        'function action() {',
        '    console.log("[pack-load-probe] required " + required + " module(s), " +',
        '        failed.length + " failed");',
        '    for (var j = 0; j < failed.length; j++) console.log("  ❌ " + failed[j]);',
        '    if (failed.length > 0) {',
        '        throw new Error("pack runtime load self-test FAILED: " +',
        '            failed.length + " module(s) did not load");',
        '    }',
        '    if (required === 0) {',
        '        throw new Error("pack runtime load self-test FAILED: no .js required");',
        '    }',
        '    return { success: true, required: required };',
        '}',
    ];
    return lines.join('\n') + '\n';
}

/** The generated JSRunner config pointing at the probe. */
function renderProbeConfig(jsPath) {
    return JSON.stringify({
        name: 'JSRunner',
        params: {
            jsPath: jsPath,
            jobParams: {}
        }
    }, null, 2) + '\n';
}

module.exports = {
    probeFilesList: probeFilesList,
    renderProbeJs: renderProbeJs,
    renderProbeConfig: renderProbeConfig,
};
